version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "donotcross"
    ports:
      - "15432:5432"
    volumes:
      - /Users/esdras/ws-sds2/PostgreSQL/data:/var/lib/postgresql/data 
    networks:
      - postgres-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "bzr4@icloud.com"
      PGADMIN_DEFAULT_PASSWORD: "donotcross"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge